language: node_js

services:
  - docker

before_install:
  - docker build -t backendcodingtest_api-endpoint .
  - docker run -d -p 127.0.0.1:8010:8010 backendcodingtest_api-endpoint /bin/sh -c "npm test;"

script:
  - npm test